<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\PurchaseOrder\Block\PurchaseOrder\Info\NegotiableQuote $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<?php if ($block->isFromNegotiableQuote()): ?>
    <?php $negotiableQuote = $block->getNegotiableQuote(); ?>
    <div id="negotiable-quote-name" class="purchase-order-reference-content">
        <strong><span><?= $escaper->escapeHtml(__('Quote:')) ?></span></strong>
        <a href="<?= $escaper->escapeUrl($block->getNegotiableQuoteUrl($negotiableQuote->getQuoteId()));?>"
           target="_blank"
           title="<?= $escaper->escapeHtmlAttr(__('View Negotiable Quote'));?>"
           class="btn-close action close">
            <span><?= $escaper->escapeHtml($negotiableQuote->getQuoteName());?></span>
        </a>
    </div>
<?php endif; ?>
