<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\PurchaseOrder\Block\Order\Info\PurchaseOrder $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\PurchaseOrder\Api\Data\PurchaseOrderInterface $purchaseOrder
 */
?>
<?php if ($block->isFromPurchaseOrder()): ?>
    <?php $purchaseOrder = $block->getLinkedPurchaseOrder(); ?>
    <div id="purchase-order-number" class="order-reference-content">
        <strong><span><?= $escaper->escapeHtml(__('Purchase Order Number:')) ?></span></strong>
        <a href="<?= $escaper->escapeUrl($block->getPurchaseOrderUrl($purchaseOrder->getEntityId()));?>"
           target="_blank"
           title="<?= $escaper->escapeHtmlAttr(__('View Purchase Order'));?>"
           class="btn-close action close">
            <span>#<?= $escaper->escapeHtml($purchaseOrder->getIncrementId());?></span>
        </a>
    </div>
<?php endif; ?>
