<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $block Magento\CompanyShipping\Block\Adminhtml\System\Config\ShippingMethods */ ?>
<script type="text/x-magento-init">
{
    ".applicable-shipping-methods": {
        "Magento_CompanyShipping/js/form/element/select/dependent-field": {
            "availableShippingMethodsSelector":
                "#btob_website_configuration_default_b2b_shipping_methods_available_shipping_methods",
            "enableCompanyFieldSelector": "#btob_website_configuration_company_active"
        }
    }
}
</script>
