<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\RequisitionList\Block\Catalog\Product\ProductList\Item\AddTo\Requisition */
/** @var $escaper \Magento\Framework\Escaper */
$productSku = $block->getProduct()->getSku();
?>
<div class="block block-requisition-list social-button"
     data-bind="scope: 'requisition_<?= (int) $block->getComponentId() ?>'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "requisition_<?= (int) $block->getComponentId() ?>": {
                        "component": "Magento_RequisitionList/js/requisition/action/product/add",
                        "editModuleName": "requisition_<?= (int) $block->getComponentId() ?>.edit",
                        "title": "<?= $escaper->escapeJs(__('Add to Requisition List')) ?>",
                        "action": "<?= $escaper->escapeUrl($block->getUrl('requisition_list/item/add')) ?>",
                        "sku": "<?= $escaper->escapeJs($block->getProduct()->getSku()) ?>",
                        "productFormSelector": "form[data-product-sku='<?= $escaper->escapeJs($productSku) ?>']"
                    },
                    "requisition_<?= (int) $block->getComponentId() ?>.edit": {
                        "component": "Magento_RequisitionList/js/requisition/list/edit",
                        "modal": "add_to_requisition_popup",
                        "saveUrl": "<?= $escaper->escapeUrl($block->getUrl('rest/V1/requisition_lists')) ?>"
                    }
                }
            }
        }
    }
</script>
