<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\PurchaseOrder\Block\PurchaseOrder\History $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<div class="purchase-order-comments-block">
    <div class="comments-block-list">
        <?php foreach ($block->getPurchaseOrderLogs() as $log): ?>
            <?php $logMessage = $block->getLogMessage($log);?>
            <?php if (!$logMessage) {continue;} ?>
            <div class="comments-block-item">
                <span class="comments-block-item-date-time">
                    <?= $escaper->escapeHtml(
                        $block->formatDate($log->getCreatedAt(), \IntlDateFormatter::MEDIUM, true)
                    ) ?>
                </span>
                <div class="comments-block-item-comment">
                    <?= /* @noEscape */ nl2br($escaper->escapeHtml($logMessage)) ?>
                </div>
            </div>
        <?php endforeach ?>
    </div>
</div>
