<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/* @var \Magento\NegotiableQuote\Block\Adminhtml\Sales\Order\Create\Sku\Errors $block
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<div data-mage-init='{"Magento_NegotiableQuote/quote/create/init-errors": {
    "listType" : "<?= $block->escapeHtml($block->getListType()) ?>",
    "url" : "<?= $block->escapeHtml($block->getConfigureUrl()) ?>"}
}' class="fieldset-wrapper admin__fieldset-wrapper">
    <div class="fieldset-wrapper-title admin__fieldset-wrapper-title">
        <div class="message message-notice">
            <span>
                <span id="sku-attention-num"><?= (int) $block->getNumberOfFailed() ?></span>
                <?= $block->escapeHtml(__('product(s) require attention.')) ?>
            </span>
        </div>
        <strong class="title"><?= $block->escapeHtml(__('Products Not Added to the Quote')) ?></strong>
        <div id="sku_errors_actions" class="actions">
            <?=
            $block->getButtonHtml(
                __('Add Products to Quote'),
                'addBySku.submitConfigured()',
                'action-add'
            ); ?>
            <button title="<?= $block->escapeHtmlAttr(__('Remove All')) ?>"
                    type="button"
                    class="action-default action-delete">
                <?= /* @noEscape */ $secureRenderer->renderEventListenerAsTag(
                    'onclick',
                    'addBySku.removeAllFailed()',
                    '#sku_errors_actions .action-delete'
                );  ?>
                <span><?= $block->escapeHtml(__('Remove All')) ?></span>
            </button>
        </div>
    </div>
    <?= $block->getChildHtml() ?>
</div>
