<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php if ($block->isNegotiableQuote()) : ?>
    <tr>
        <th><?= $block->escapeHtml(__('Order Placed From Quote')) ?></th>
        <td>
            <span><?= $block->escapeHtml($block->getViewQuoteLabel()) ?></span>
            <a href="<?= $block->escapeUrl($block->getViewQuoteUrl()) ?>">
                <span><?= $block->escapeHtml($block->getQuoteName()) ?></span>
            </a>
        </td>
    </tr>
<?php endif; ?>
