<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\PurchaseOrder\Block\PurchaseOrder\EmailTotals $block
 * @var \Magento\Framework\Escaper $escaper
 */

// Get Purchase Order id from email template
$purchaseOrderId = $block->getPurchaseOrderId();
$block->setPurchaseOrderById($purchaseOrderId);
?>
<?php foreach ($block->getEmailTotals() as $code => $total): ?>
    <?php if ($total->getBlockName()): ?>
        <?= $block->getChildHtml($total->getBlockName(), false) ?>
    <?php else: ?>
        <?php $style = ($total->getStyle() ? ' ' . $total->getStyle() : ''); ?>
        <tr class="<?= $escaper->escapeHtml($code . $style) ?>">
            <th colspan="2" <?= $escaper->escapeHtml($block->getLabelProperties()) ?> scope="row">
                <?php if ($total->getStrong()): ?>
                <strong>
                    <?= $escaper->escapeHtml($total->getLabel()) ?>
                </strong>
                <?php else: ?>
                    <?= $escaper->escapeHtml($total->getLabel()) ?>
                <?php endif; ?>
            </th>
            <td <?= $escaper->escapeHtml($block->getValueProperties()) ?>
                data-th="<?= $escaper->escapeHtml($total->getLabel()) ?>">
                <?php if ($total->getStrong()): ?>
                <strong>
                    <?= $escaper->escapeHtml(
                        $block->formatPrice(
                            $total->getValue(),
                            $total->getCurrency() ? $total->getCurrency() : $block->getQuote()->getQuoteCurrencyCode()
                        ),
                        ['span']
                    ) ?>
                </strong>
                <?php else: ?>
                    <?= $escaper->escapeHtml(
                        $block->formatPrice(
                            $total->getValue(),
                            $total->getCurrency() ? $total->getCurrency() : $block->getQuote()->getQuoteCurrencyCode()
                        ),
                        ['span']
                    ) ?>
                <?php endif; ?>
            </td>
        </tr>
    <?php endif; ?>
<?php endforeach ?>
