<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var $block \Magento\PurchaseOrder\Block\PurchaseOrder\Totals\Original
 * @var $escaper \Magento\Framework\Escaper
 */
?>
<?php $total = $block->getTotal() ?>
<tr class="<?= $escaper->escapeHtml($total->getCode()) ?>_table">
    <td <?= $escaper->escapeHtml($block->getValueProperties()) ?>
            data-th="<?= $escaper->escapeHtml($total->getLabel()) ?>" colspan="2">
        <div id="toggle-part" class="collapsible-table" data-role="catalog-price">
            <table class="data-table">
                <tbody>
                <?php foreach ($total->getSubtotals() as $key => $option): ?>
                    <tr class="<?= $escaper->escapeHtml($key . ' ' . $option['class']) ?>">
                        <th scope="row">
                            <?= $escaper->escapeHtml($option['label']) ?>
                        </th>
                        <td data-th="<?= $escaper->escapeHtml($option['label']) ?>">
                            <?= /* @noEscape */ $block->displayPrices($option['value'], $total->getCurrency()) ?>
                        </td>
                    </tr>
                <?php endforeach ?>
                </tbody>
            </table>
        </div>
        <table class="data-table toggle-action"
               data-mage-init='{"Magento_NegotiableQuote/js/quote/actions/toggle-show":{
               "toggleBlockId": "toggle-part",
               "delay": 300,
               "toggleClass": {
                "element" : "[data-action=toggle-arrow]",
                "class" : "active"
               }
               }}'>
            <tbody>
            <tr class="<?= $escaper->escapeHtml($total->getCode()) ?>">
                <th scope="row">
                    <span data-action="toggle-arrow" class="toggle">
                        <?= $escaper->escapeHtml($total->getLabel()) ?>
                    </span>
                </th>
                <td data-th="<?= $escaper->escapeHtml($total->getLabel()) ?>">
                    <?= /* @noEscape */ $block->displayPrices($total->getValue(), $total->getCurrency()) ?>
                </td>
            </tr>
            </tbody>
        </table>
    </td>
</tr>
