<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var $block \Magento\CompanyCredit\Block\Info\CompanyCredit
 * @var $escaper \Magento\Framework\Escaper
 */
?>
<dl class="payment-method purchase order" id="order-payment-information">
    <dt class="title"><?= $escaper->escapeHtml($block->getMethod()->getTitle()) ?></dt>
    <dd class="content">
        <?php if ($block->getInfo()->getPoNumber()): ?>
        <strong><?= $escaper->escapeHtml(__('Custom Reference Number')) ?></strong>
        <span class="number"><?= $block->escapeHtml($block->getInfo()->getPoNumber()) ?></span>
        <?php endif; ?>
    </dd>
    <dd class="content">
        <?php if ($block->isCurrencyDifferent()): ?>
            <strong><?= $escaper->escapeHtml(__('Charged off the company credit')) ?></strong>
            <span class="number"><?= /* @noEscape */ $block->getChargedAmount() ?></span>
        <?php endif; ?>
    </dd>
</dl>
