<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\NegotiableQuote\Block\Quote\Info\Order $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<?php $order = $block->getOrder(); ?>
<?php if ($order): ?>
        <div id="order-number" class="quote-reference-content">
            <strong><span><?= $escaper->escapeHtml(__('Order Number:')) ?></span></strong>
            <a href="<?= $escaper->escapeUrl($block->getOrderUrl($order->getId()));?>"
               target="_blank"
               title="<?= $escaper->escapeHtmlAttr(__('View Order'));?>"
               class="btn-close action close">
                <span>#<?= $escaper->escapeHtml($order->getIncrementId());?></span>
            </a>
        </div>
<?php endif; ?>
