<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var $block \Magento\Company\Block\Company\Role\Edit
 * @var $escaper \Magento\Framework\Escaper
 */

$role = $block->getRole();
?>

<form class="form form-edit-role" method="post" id="role-edit-form"
      action="<?= $block->escapeUrl($block->getUrl('*/*/editPost', ['id' => $role->getId()])) ?>"
      data-mage-init='{"validation":{}}'>
    <?= $block->getBlockHtml('formkey') ?>

    <fieldset class="fieldset info">
        <legend class="legend"><span><?= $block->escapeHtml(__('Role Information')) ?></span></legend>
        <div class="field role-name _required">
            <label class="label" for="role_name">
                <span><?= $block->escapeHtml(__('Role Name')) ?></span>
            </label>
            <div class="control">
                <input type="text" name="role_name" id="role_name"
                       value="<?= $block->escapeHtmlAttr($role->getRoleName()) ?>"
                       title="<?= $block->escapeHtmlAttr(__('Role Name')) ?>"
                       data-async-is-valid="true"
                       data-mage-init='{"Magento_Company/js/form/element/async-validation": {
                            "name": "company_role_name",
                            "validateUrl": "<?= $block->escapeUrl($block->getUrl('company/role/validate')) ?>"
                       }}'
                       data-validate="{required:true, 'validate-async-company-role-name': true}"
                       class="input-text">
            </div>
        </div>
    </fieldset>

    <fieldset class="fieldset info">
        <legend class="legend"><span><?= $block->escapeHtml(__('Role Permissions')) ?></span></legend>
        <p class="note">
            <?= $escaper->escapeHtml(__('Granting permissions does not affect which features are
            available for your company account. The merchant must enable features to make
            them available for your account.')) ?>
        </p>
        <div class="box-actions">
            <button class="action expand" data-action="expand-tree" type="button">
                <span><?= $block->escapeHtml(__('Expand All')) ?></span>
            </button>
            <button class="action expand" data-action="collapse-tree" type="button">
                <span><?= $block->escapeHtml(__('Collapse All')) ?></span>
            </button>
        </div>
        <?php
        // This is a temporary solution for backward compatibility because we cannot modify block public api methods
        // Modify getTreeJsOptions methods in minor version for it to return array without roleTree key
        $treeJsOptions = $block->getTreeJsOptions();
        $treeOptions = $treeJsOptions['roleTree'];
        ?>
        <div class="tree x-tree" id="role-tree" data-role="role-tree"
             data-mage-init='{"roleTree":<?= /* @noEscape */ $block->getJsonHelper()->jsonEncode($treeOptions)?>}'>
        </div>
        <input type="hidden" name="role_permissions" />
    </fieldset>

    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action save primary" title="<?= $block->escapeHtmlAttr(__('Save Role')) ?>">
                <span><?= $block->escapeHtml(__('Save Role')) ?></span>
            </button>
        </div>
    </div>
</form>
