<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<?php
/**
 * @var $block \Magento\NegotiableQuote\Block\Adminhtml\Quote\View\Errors\GridContainer
 */
?>
<div id="itemsErrors"
    data-role="items-errors"
    data-mage-init='{"Magento_NegotiableQuote/js/quote/actions/notification-modal" : {"text": "<?=
    $block->escapeHtml($block->getErrorText()) ?>", "title": "<?=$block->escapeHtml($block->getErrorTitle()) ?>"}}' ?>
</div>
