<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/* @var $block \Magento\Company\Block\Link\Company */
?>
<!-- ko scope: 'company' -->
<!-- ko if: config().is_enabled && ((hasNoCompany() && isStoreFrontRegistrationAllowed()) || isUsersViewAllowed()) -->
<li>
    <a href="<?= $block->escapeUrl($block->getHref()) ?>">
        <?= $block->escapeHtml($block->getLabel()) ?>
    </a>
</li>
<!-- /ko -->
<!-- /ko -->
