<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $block Magento\CompanyPayment\Block\System\Config\PaymentMethods */ ?>
<script type="text/x-magento-init">
{
    ".applicable-payment-methods": {
        "Magento_CompanyPayment/js/form/element/select/dependent-field": {
            "selector": "#btob_website_configuration_default_b2b_payment_methods_available_payment_methods"
        }
    }
}
</script>
