<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var Magento\Company\Block\Company\Management\Info $block
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<?php if ($block->hasCustomerCompany() && $block->isRoleEditAllowed()): ?>
    <div class="actions">
        <button type="button"
                title="<?= $block->escapeHtmlAttr(__('Add New Role')) ?>"
                id="add-new-role"
                class="action primary"
                data-mobile-label="<?= $block->escapeHtmlAttr(__('Add New Role')) ?>">
            <span><?= $block->escapeHtml(__('Add New Role')) ?></span>
        </button>
        <?php $url = $block->escapeJs($block->getUrl('*/*/edit')); ?>
        <?= /* @noEscape */ $secureRenderer->renderEventListenerAsTag(
            'onclick',
            "location = ('{$url}')",
            '.actions #add-new-role'
        ); ?>
    </div>
<?php endif; ?>
